= Hands-on Disaster Recovery of OpenShift containers and VMs with Trident protect

This lab guide provides a walkthrough on using NetApp Trident Protect to enable Distaster Recovery Plan for both your VMs and your containers between two environments.

You will go through the steps to install the NetApp Trident Container Storage Interface (CSI) driver on a ROSA cluster, as well as how to configure it to provision volumes FSx for NetApp ONTAP file system.
You will then proceed with the installation of Trident Protect, and its configuration to store data and metadata on an AWS S3 bucket.

Last, you will learn how to backup and restore a container based application, as well as failover a VM on a secondary ROSA cluster. 

NOTE: Both Trident and Trident Protect are already installed on the primary cluster.

. Module 1: Introduction & Overview
. Module 2 (Admin persona): 
.. Install and configure Trident in OpenShift (in secondary cluster)
. Module 3 (User persona):
.. Provision containers workloads
.. Provision VMs in OpenShift Virtualization
. Module 4 (Admin persona):
.. Install and configure Trident Protect in OpenShift (in secondary cluster)
. Module 5 (User persona): 
.. Backup/Restore container workloads
. Module 6 (User persona): 
.. Configure storage replication for VM workloads
.. Perform a Failover for VM workloads
. Module 7 (Bonus):
.. Restore a Virtual Machine
.. ADd a second Virtual Machine to the project and test the failover
.. Configure storage replication for container workloads
.. Perform the Failover and Failback for container workloads

[[lab-setup]]
== Lab Setup

=== Authenticate `oc` to the cluster

The bastion provided with the RHDP workshop has the `aws` and `rosa` command line tools already installed and logged in.  The `oc` command is installed, but not authenticated.

To authenticate `oc` use the API URL, username, and password provided by the RHDP lab deployment.
